<?php
$data = array (
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '助情保养',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '助情保养',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '费洛蒙香水',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '45',
    'name' => '费洛蒙香水',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '女用调情',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '42',
    'name' => '女用调情',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => 'SM调情',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '46',
    'name' => 'SM调情',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '私处保养',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '43',
    'name' => '私处保养',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '按摩丰胸',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '44',
    'name' => '按摩丰胸',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '女性用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => '女性用品',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '调情跳蛋',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '25',
    'name' => '调情跳蛋',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '胸部刺激',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '29',
    'name' => '胸部刺激',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => 'AV震动棒',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '26',
    'name' => 'AV震动棒',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '后庭玩具',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '30',
    'name' => '后庭玩具',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '仿真阳具',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '27',
    'name' => '仿真阳具',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '双震G点棒',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '24',
    'name' => '双震G点棒',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '阴道锻炼',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '28',
    'name' => '阴道锻炼',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '润滑剂',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '7',
    'name' => '润滑剂',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '除菌消毒剂',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '54',
    'name' => '除菌消毒剂',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => '冰火润滑剂',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '51',
    'name' => '冰火润滑剂',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '功能型润滑剂',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '48',
    'name' => '功能型润滑剂',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '唇吸润滑剂',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '52',
    'name' => '唇吸润滑剂',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => '防过敏润滑剂',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '49',
    'name' => '防过敏润滑剂',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '硅油性润滑剂',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '53',
    'name' => '硅油性润滑剂',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '超滑润滑液',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '50',
    'name' => '超滑润滑液',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '水溶性润滑剂',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '47',
    'name' => '水溶性润滑剂',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '安全套',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '安全套',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '水晶套',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '38',
    'name' => '水晶套',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '润滑套套',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '35',
    'name' => '润滑套套',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '超薄套套',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '32',
    'name' => '超薄套套',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '紧致体贴',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '36',
    'name' => '紧致体贴',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '强力久战',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '33',
    'name' => '强力久战',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '早孕排卵试纸',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '37',
    'name' => '早孕排卵试纸',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '螺纹刺激',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '34',
    'name' => '螺纹刺激',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '特价套装',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '31',
    'name' => '特价套装',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '情趣服饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '情趣服饰',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '制服诱惑',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '9',
    'name' => '制服诱惑',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '情趣服饰配件',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '16',
    'name' => '情趣服饰配件',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '情趣内裤',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '13',
    'name' => '情趣内裤',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '性感睡衣',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '10',
    'name' => '性感睡衣',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '男士内裤',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '男士内裤',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '丝袜/网袜',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '11',
    'name' => '丝袜/网袜',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '连身袜/网衣',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '8',
    'name' => '连身袜/网衣',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '高档精品内衣',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '15',
    'name' => '高档精品内衣',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '三点/文胸',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '12',
    'name' => '三点/文胸',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '喷剂保养',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '5',
    'name' => '喷剂保养',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '男用震动环',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '41',
    'name' => '男用震动环',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '男用喷剂',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '39',
    'name' => '男用喷剂',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '辅助保养',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '40',
    'name' => '辅助保养',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '男性用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '男性用品',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '臀胸倒模',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '22',
    'name' => '臀胸倒模',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '名器倒模',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '19',
    'name' => '名器倒模',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '加温棒',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '23',
    'name' => '加温棒',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '前列腺按摩器',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '20',
    'name' => '前列腺按摩器',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '电动飞机杯',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '17',
    'name' => '电动飞机杯',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '男用震动环',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '21',
    'name' => '男用震动环',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '手动飞机杯',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '18',
    'name' => '手动飞机杯',
  ),
);
?>